# genres
genre_fantasy = Genre.create(name: "Fantasy")
genre_productivity = Genre.create(name: "Productivity")
genre_programming = Genre.create(name: "Programming")
genre_finance = Genre.create(name: "Finance")
genre_self_help = Genre.create(name: "Self Help")
genre_biography = Genre.create(name: "Biography")

# authors
author_brandon_sanderson = Author.create(name: "Brandon Sanderson", genre: genre_fantasy)
author_cal_newport = Author.create(name: "Cal Newport", genre: genre_productivity)
author_jim_butcher = Author.create(name: "Jim Butcher", genre: genre_fantasy)
author_robert_martin = Author.create(name: "Robert Martin", genre: genre_programming)
author_michael_lewis = Author.create(name: "Michael Lewis", genre: genre_finance)
author_sandi_metz = Author.create(name: "Sandi Metz", genre: genre_programming)

# jsons
# jim butcher
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Battle Ground".titlecase, rating: "4.09")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Brief cases".titlecase, rating: "3.36")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Shadowed souls".titlecase, rating: "4.24")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "The aeronaut's windlass".titlecase, rating: "4.85")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Peace Talks".titlecase, rating: "3.51")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Skin Game".titlecase, rating: "4.89")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Cold Days".titlecase, rating: "3.48")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Ghost Story".titlecase, rating: "4.51")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Changes".titlecase, rating: "3.45")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Side Jobs".titlecase, rating: "3")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Small Favor".titlecase, rating: "4.39")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Captain's Fury".titlecase, rating: "3.53")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Turn Coat".titlecase, rating: "3.02")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Mean Streets".titlecase, rating: "3.79")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "First lord's fury".titlecase, rating: "4.33")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Turn Coat".titlecase, rating: "3.79")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Backup".titlecase, rating: "4.03")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Jim Butcher's the Dresden files".titlecase, rating: "3.69")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Princeps' Fury".titlecase, rating: "4.87")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Cursor's Fury".titlecase, rating: "4.76")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "White Night".titlecase, rating: "4.11")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Dead Beat".titlecase, rating: "4.91")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Proven Guilty".titlecase, rating: "3.17")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Academ's Fury".titlecase, rating: "3.75")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Grave Peril".titlecase, rating: "3.37")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Blood Rites".titlecase, rating: "4.3")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Furies of Calderon".titlecase, rating: "4.24")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Death Masks".titlecase, rating: "4.51")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Summer Knight".titlecase, rating: "3.79")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Fool Moon".titlecase, rating: "4.41")
Book.create(author: author_jim_butcher, genre: genre_fantasy, title: "Storm Front".titlecase, rating: "3.02")

## michael lewis
Book.create(author: author_michael_lewis, genre: genre_finance, title: "The Fifth Risk".titlecase, rating: "3.21")
Book.create(author: author_michael_lewis, genre: genre_biography, title: "The undoing project".titlecase, rating: "4.2")
Book.create(author: author_michael_lewis, genre: genre_finance, title: "The big short".titlecase, rating: "4.33")
Book.create(author: author_michael_lewis, genre: genre_finance, title: "Flash Boys".titlecase, rating: "4.15")
Book.create(author: author_michael_lewis, genre: genre_finance, title: "Boomerang".titlecase, rating: "4.71")
Book.create(author: author_michael_lewis, genre: genre_finance, title: "Money Culture".titlecase, rating: "4.82")
Book.create(author: author_michael_lewis, genre: genre_finance, title: "Liar's Poker".titlecase, rating: "4.47")
Book.create(author: author_michael_lewis, genre: genre_finance, title: "The Real Price of Everything".titlecase, rating: "4.43")
Book.create(author: author_michael_lewis, genre: genre_finance, title: "Ecommerce".titlecase, rating: "3.42")
Book.create(author: author_michael_lewis, genre: genre_finance, title: "Operations Strategy".titlecase, rating: "3.26")
Book.create(author: author_michael_lewis, genre: genre_finance, title: "The money culture".titlecase, rating: "3.76")
Book.create(author: author_michael_lewis, genre: genre_finance, title: "Pacific rift".titlecase, rating: "3.61")

# sandi metz
Book.create(author: author_sandi_metz, genre: genre_programming, title: "Practical Object-Oriented Design".titlecase, rating: "4.81")
Book.create(author: author_sandi_metz, genre: genre_programming, title: "99 Bottles of OOP".titlecase, rating: "4.4")

# bob martin
Book.create(author: author_robert_martin, genre: genre_programming, title: "Clean Agile".titlecase, rating: "3.46")
Book.create(author: author_robert_martin, genre: genre_programming, title: "Clean Architecture".titlecase, rating: "3.38")
Book.create(author: author_robert_martin, genre: genre_programming, title: "The clean coder".titlecase, rating: "3.01")
Book.create(author: author_robert_martin, genre: genre_programming, title: "Clean Code".titlecase, rating: "4.89")
Book.create(author: author_robert_martin, genre: genre_programming, title: "More C++ Gems".titlecase, rating: "4.27")
Book.create(author: author_robert_martin, genre: genre_programming, title: "Pattern languages of program design 3".titlecase, rating: "3.22")
Book.create(author: author_robert_martin, genre: genre_programming, title: "Designing object-oriented C++ applications using the Booch method".titlecase, rating: "3.3")

Book.create(author: author_robert_martin, genre: genre_self_help, title: "Practical speech for modern business".titlecase, rating: "3.71")

# brandon sanderson
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Frugal Wizard's Handbook for Surviving Medieval England".titlecase, rating: "3.01")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Defiant".titlecase, rating: "4.08")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Yumi and the Nightmare Painter".titlecase, rating: "3.61")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "The Sunlit Man".titlecase, rating: "4.65")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Long Chills and Case Dough".titlecase, rating: "3.05")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Tress of the Emerald Sea".titlecase, rating: "4.9")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Lost Metal".titlecase, rating: "3.19")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Defending Elysium".titlecase, rating: "3.8")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Cytonic".titlecase, rating: "4.03")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Rhythm of War".titlecase, rating: "3.45")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Dawnshard".titlecase, rating: "4.54")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Starsight".titlecase, rating: "4.66")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Mistborn".titlecase, rating: "4.16")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Legion: Lies of the Beholder".titlecase, rating: "3.56")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Infinity blade".titlecase, rating: "3.37")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Skyward".titlecase, rating: "3.41")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Legion".titlecase, rating: "4.86")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Dreamer".titlecase, rating: "4.86")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Oathbringer".titlecase, rating: "3.65")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Edgedancer".titlecase, rating: "4.54")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Arcanum Unbounded".titlecase, rating: "3.37")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "The Dark Talent".titlecase, rating: "4.39")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "White Sand".titlecase, rating: "3.62")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "The Bands of Mourning".titlecase, rating: "3.42")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Firefight".titlecase, rating: "3.14")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Shadows for Silence in the Forests of Hell".titlecase, rating: "3.22")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Shadows of Self".titlecase, rating: "3.98")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Mitosis".titlecase, rating: "4.62")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Tales from the Cosmere".titlecase, rating: "4.92")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "The Rithmatist".titlecase, rating: "4.08")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Steelheart".titlecase, rating: "4.6")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Words of Radiance".titlecase, rating: "4.7")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Emperor's Soul".titlecase, rating: "3.6")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Alcatraz vs. the Evil Librarians".titlecase, rating: "4.85")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Alloy of Law".titlecase, rating: "3.01")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Final Empire".titlecase, rating: "3.83")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "Alcatraz versus the Shattered Lens".titlecase, rating: "3.19")
Book.create(author: author_brandon_sanderson, genre: genre_fantasy, title: "The Way of Kings".titlecase, rating: "4.43")

# cal newport
Book.create(author: author_cal_newport, genre: genre_productivity, title: "Slow Productivity".titlecase, rating: "4.88")
Book.create(author: author_cal_newport, genre: genre_productivity, title: "A World Without Email".titlecase, rating: "3.91")
Book.create(author: author_cal_newport, genre: genre_productivity, title: "Time-Block Planner".titlecase, rating: "4.42")
Book.create(author: author_cal_newport, genre: genre_self_help, title: "Digital Minimalism".titlecase, rating: "3.95")
Book.create(author: author_cal_newport, genre: genre_self_help, title: "Deep Work".titlecase, rating: "4.24")
Book.create(author: author_cal_newport, genre: genre_self_help, title: "So Good They Can't Ignore You".titlecase, rating: "4.75")
Book.create(author: author_cal_newport, genre: genre_productivity, title: "How to be a High School Superstar".titlecase, rating: "3.24")
Book.create(author: author_cal_newport, genre: genre_productivity, title: "Stress-free college admissions".titlecase, rating: "4.18")
Book.create(author: author_cal_newport, genre: genre_productivity, title: "How to Become a Straight-A Student".titlecase, rating: "3.42")
Book.create(author: author_cal_newport, genre: genre_productivity, title: "How to win at college".titlecase, rating: "4.11")